version: '3.8'
services:
    instashare-admin:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: instashare-admin
        command: 'php artisan serve --host=0.0.0.0'
        volumes:
            - .:/app
        ports:
            - 8000:8000
        networks:
            - instashare
        depends_on:
            - rabbitmq
            - minio
            - pgsql
            
    instashare-admin-dbqueue:
        build:
          context: .
          dockerfile: Dockerfile
        command: 'php artisan queue:work'
        volumes:
            - .:/app
        networks:
          - instashare
        depends_on:
          - pgsql
          - minio

    instashare-admin-rbqueue:
        build:
          context: .
          dockerfile: Dockerfile
        command: 'php artisan queue:work rabbitmq'
        volumes:
            - .:/app
        networks:
          - instashare
        depends_on:
          - pgsql
          - rabbitmq
          - minio

    pgsql:
        image: postgres:14
        container_name: pgsql_container
        ports:
            - 5435:5432
        environment:
            PGPASSWORD: instadmin*2022
            POSTGRES_DB: instashare-admin
            POSTGRES_USER: instashare
            POSTGRES_PASSWORD: instadmin*2022
        volumes:
            - ./storage/dbdata:/var/lib/postgresql/data
        networks:
            - instashare

    minio:
        image: 'minio/minio:latest'
        container_name: minio_container
        ports:
            - 9000:9000
            - 8900:8900
        environment:
            MINIO_ROOT_USER: instashare
            MINIO_ROOT_PASSWORD: instadmin*2022
        volumes:
            - ./storage/miniodata:/data/minio
        networks:
            - instashare
        command: minio server /data/minio --console-address ":8900"

    rabbitmq:
        image: rabbitmq:3.9-management
        container_name: rabbitmq_container
        ports:
            - 15672:15672
            - 5672:5672
        networks:
            - instashare

networks:
    instashare:
      external:
        name: instashare

